### ISSUE TITLE
Create a Python library to execute Arcaflow workflows

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/lib-arcaflow-python#1]
## Please describe what you would like to see in this project

Create a Python library that executes the Arcaflow engine and release it on PyPI. This will allow Python tools to execute Arcaflow workflows without needing to do extra work.

## Please describe your use case

Embedding Arcaflow workflows into specialized tools, such as Krkn.

**Comment by dustinblack** [comment]
Closed with https://github.com/arcalot/arcaflow-engine/pull/47
